
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
    push

jobs:
  crawlclima:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    env:
      COMPOSE_FILE: docker/database-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: poc-dbchemas
        # environment-file: environment.yml
        # channels: conda-forge

    - name: Copy env_file as env
      shell: bash -l {0}
      run: |
        make deploy
